version: "3"  # optional since v1.27.0
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "3003:3000" 
     
    volumes:
      - /var/app/node_modules
      - .:/var/app

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "3003:3000" 
     
    volumes:
      - /var/app/node_modules
      - .:/var/app

    command: ["npm","run","test"]
      